# Generated by Django 4.2.5 on 2023-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestoMateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('cp', models.CharField(max_length=8)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Contacto',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='nombre',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='camada',
        ),
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='disponible',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
